# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-04 02:43-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pinakes/common/auth/keycloak_django/authentication.py:76
msgid "Invalid authorization header. No credentials provided."
msgstr "En-tête de token non valide. Aucune information d'identification fournie."

#: pinakes/common/auth/keycloak_django/authentication.py:80
msgid ""
"Invalid authorization header. Credentials string should not contain spaces."
msgstr "En-tête d'autorisation non valide. La chaîne des informations d'identification ne doit pas contenir d'espaces."

#: pinakes/common/auth/keycloak_django/authentication.py:107
msgid "No valid JWK found."
msgstr "Aucun JWK valide n'a été trouvé."

#: pinakes/common/auth/keycloak_django/authentication.py:119
msgid "Signature has expired."
msgstr "La licence est arrivée à expiration."

#: pinakes/common/auth/keycloak_django/authentication.py:121
msgid "Invalid claims."
msgstr "Revendications non valables."

#: pinakes/common/auth/keycloak_django/authentication.py:123
msgid "Invalid signature."
msgstr "Signature invalide."

#: pinakes/common/auth/keycloak_django/authentication.py:163
msgid "Token expired"
msgstr "Token expiré"

#: pinakes/common/auth/keycloak_django/authentication.py:168
#: pinakes/common/auth/keycloak_django/authentication.py:172
msgid "Invalid audience"
msgstr "Public non valide"

#: pinakes/common/exception_handler.py:27
msgid "Internal Error"
msgstr "Erreur interne"

#: pinakes/common/exception_handler.py:31
msgid "{}. Report to the support team if it is not an user error."
msgstr "{}. Si ce n'est pas une erreur de l'utilisateur, signalez-le à l'équipe d'assistance."

#: pinakes/common/exception_handler.py:37
msgid "Unauthorized"
msgstr "Non autorisé"

#: pinakes/common/image_mixin.py:43
msgid "{} object has no attribute 'icon'."
msgstr "{} objet n’a pas d’icône d’attribution"

#: pinakes/common/image_mixin.py:69
msgid "Icon attribute has been set on {} object (id: {})."
msgstr "L’attribut de l’icône a été défini sur {} objet (id: {})."

#: pinakes/common/image_mixin.py:95 pinakes/common/image_mixin.py:123
msgid "Icon attribute has not been set on {} object (id: {})."
msgstr "L’attribut de l’icône n’a pas été défini sur {} objet (id: {})."

#: pinakes/common/models/fields.py:14
msgid "An encrypted JSON object"
msgstr "Un objet JSON crypté"

#: pinakes/main/analytics/analytics_collectors.py:23
msgid "General platform configuration."
msgstr "Configuration générale de la plate-forme."

#: pinakes/main/analytics/analytics_collectors.py:64
msgid "Data on sources"
msgstr "Données sur les sources"

#: pinakes/main/analytics/analytics_collectors.py:89
msgid "Data on service_offerings"
msgstr "Données sur les offres de service"

#: pinakes/main/analytics/analytics_collectors.py:119
msgid "Data on service_offering_nodes"
msgstr "Données sur les nœuds d'offre de service"

#: pinakes/main/analytics/analytics_collectors.py:150
msgid "Data on service_instances"
msgstr "Données sur instances de service"

#: pinakes/main/analytics/analytics_collectors.py:180
msgid "Data on service_inventories"
msgstr "Données sur les inventaires de services"

#: pinakes/main/analytics/analytics_collectors.py:209
msgid "Data on portfolios"
msgstr "Données sur les portefeuilles"

#: pinakes/main/analytics/analytics_collectors.py:236
msgid "Data on portfolio_items"
msgstr "Données sur les éléments de portefeuille"

#: pinakes/main/analytics/analytics_collectors.py:267
msgid "Data on orders"
msgstr "Données sur les commandes"

#: pinakes/main/analytics/analytics_collectors.py:294
msgid "Data on order_items"
msgstr "Données sur les articles de la commande"

#: pinakes/main/analytics/analytics_collectors.py:328
msgid "Data on approval_requests"
msgstr "Données sur les demandes d’approbation"

#: pinakes/main/analytics/analytics_collectors.py:355
msgid "Data on service_plans"
msgstr "Données sur les plans de service"

#: pinakes/main/analytics/analytics_collectors.py:383
msgid "Data on templates"
msgstr "Données de modèles "

#: pinakes/main/analytics/analytics_collectors.py:407
msgid "Data on workflows"
msgstr "Données sur les flux de travail"

#: pinakes/main/analytics/analytics_collectors.py:434
msgid "Data on requests"
msgstr "Données sur les demandes"

#: pinakes/main/analytics/analytics_collectors.py:469
msgid "Data on actions"
msgstr "Données sur les actions"

#: pinakes/main/analytics/analytics_collectors.py:495
msgid "Data on tag_links"
msgstr "Données sur les liens de libellé"

#: pinakes/main/analytics/analytics_collectors.py:522
msgid "Data on groups"
msgstr "Données sur les groupes"

#: pinakes/main/analytics/analytics_collectors.py:544
msgid "Counts of orders by products"
msgstr "Nombre de commandes par produit"

#: pinakes/main/analytics/analytics_collectors.py:581
msgid "Counts of tags by portfolios"
msgstr "Nombre de libellés par portefeuille"

#: pinakes/main/analytics/analytics_collectors.py:615
msgid "Counts of tags by products"
msgstr "Nombre d'étiquettes par produit"

#: pinakes/main/analytics/analytics_collectors.py:649
msgid "Counts of tags by service_intentories"
msgstr "Nombre de libellés par inventaire de service"

#: pinakes/main/analytics/analytics_collectors.py:683
msgid "Order data by product"
msgstr "Données de commande par produit"

#: pinakes/main/analytics/analytics_collectors.py:783
msgid "Approval request time spent by group"
msgstr "Temps consacré aux demandes d'approbation par groupe"

#: pinakes/main/approval/exceptions.py:8
msgid "Insufficient query parameters"
msgstr "Pas suffisamment de paramètres de recherche"

#: pinakes/main/approval/exceptions.py:13
msgid "Invalid State Transition"
msgstr "Transition d’état non valide"

#: pinakes/main/approval/exceptions.py:18
msgid "Field cannot be blank"
msgstr "Le champ ne peut rester vide"

#: pinakes/main/approval/exceptions.py:23
msgid "Duplicated UUID for approver groups"
msgstr "UUID dupliqué pour les groupes d’approbation"

#: pinakes/main/approval/exceptions.py:28
msgid "Group has no approver role"
msgstr "Le groupe n’a pas de rôle d’approbation"

#: pinakes/main/approval/exceptions.py:33
msgid "Group does not exist"
msgstr "Le groupe n'existe pas."

#: pinakes/main/approval/exceptions.py:38
msgid "There are resource objects linked to the workflow"
msgstr "Il existe des objets ressources liés au flux de travail"

#: pinakes/main/approval/exceptions.py:43
msgid "Workflow is in use"
msgstr "Le flux de travail est en cours d'utilisation"

#: pinakes/main/approval/services/create_action.py:49
msgid "The memo message cannot be blank"
msgstr "Le message memo ne peut pas rester vide"

#: pinakes/main/approval/services/create_action.py:56
msgid "Current request is not pending state"
msgstr "La demande actuelle n’est pas dans l’état «en attente»"

#: pinakes/main/approval/services/create_action.py:64
msgid "Current request is not started state"
msgstr "La demande actuelle n’est pas dans l’état «démarrée»"

#: pinakes/main/approval/services/create_action.py:72
msgid "Current request is not in pending state"
msgstr "La demande actuelle n’est pas dans l’état «en attente»"

#: pinakes/main/approval/services/create_action.py:80
#: pinakes/main/approval/services/create_action.py:97
msgid "Current request is not in notified state"
msgstr "La demande actuelle n’est pas dans l’état «notifié»"

#: pinakes/main/approval/services/create_action.py:85
msgid "Only child level request can be approved"
msgstr "Seules des demandes de niveau «dépendant» peuvent être acceptées"

#: pinakes/main/approval/services/create_action.py:102
msgid "Only child level request can be denied"
msgstr "Seules des demandes de niveau «dépendant» peuvent être refusées"

#: pinakes/main/approval/services/create_action.py:107
msgid "A reason has to be provided if a request is being denied"
msgstr "Une raison doit être avancée si une demande est refusée"

#: pinakes/main/approval/services/create_action.py:119
msgid "Only root level request can be canceled"
msgstr "Seules les demandes de niveau «racine» peuvent être annulées."

#: pinakes/main/approval/services/create_action.py:124
msgid "The request has already finished"
msgstr "La demande est déjà terminée"

#: pinakes/main/approval/services/create_action.py:136
msgid "Current request has already finished"
msgstr "La demande actuelle est déjà terminée"

#: pinakes/main/approval/services/create_action.py:140
msgid "Failure reason is missing"
msgstr "La raison de l’échec est manquante"

#: pinakes/main/approval/services/create_action.py:144
msgid "Only child level request can be flagged error"
msgstr "Seules des demandes de niveau «dépendant» peuvent être indiquées en tant qu’erreur"

#: pinakes/main/approval/services/email_notification.py:92
msgid "Failed to email group {}"
msgstr "N’a pas pu envoyer d’email au groupe {}"

#: pinakes/main/approval/services/update_request.py:19
msgid "Auto-approved"
msgstr "Auto-approuvées"

#: pinakes/main/approval/validations.py:58
msgid "Group id {} does not exist"
msgstr "Id Group {} n’existe pas"

#: pinakes/main/approval/validations.py:66
msgid "Group {} does not have approver role"
msgstr "Le group {} ne possède pas de rôle d’approbation"

#: pinakes/main/approval/views.py:186
msgid "Insufficient resource object params: {}"
msgstr "Paramètres d’objets de ressources insuffisants: {}"

#: pinakes/main/auth/views.py:58
msgid "Logout is not supported with Bearer auth."
msgstr "La déconnexion n'est pas supportée avec l'authentification par Bearer."

#: pinakes/main/catalog/exceptions.py:8
msgid "Bad query parameters"
msgstr "Mauvais paramètres de demande"

#: pinakes/main/catalog/exceptions.py:13
msgid "Invalid survey"
msgstr "Questionnaire non valide"

#: pinakes/main/catalog/exceptions.py:18
msgid "Uncancelable Order"
msgstr "Commande non annulable"

#: pinakes/main/catalog/models.py:190
msgid "Info"
msgstr "Info"

#: pinakes/main/catalog/models.py:191
msgid "Error"
msgstr "Erreur"

#: pinakes/main/catalog/models.py:192
msgid "Warning"
msgstr "Avertissement"

#: pinakes/main/catalog/models.py:193
msgid "Debug"
msgstr "Déboguer"

#: pinakes/main/catalog/models.py:332 pinakes/main/catalog/models.py:419
msgid "Approval Pending"
msgstr "En attente d’approbation"

#: pinakes/main/catalog/models.py:333 pinakes/main/catalog/models.py:420
msgid "Approved"
msgstr "Approuvé"

#: pinakes/main/catalog/models.py:334 pinakes/main/catalog/models.py:421
msgid "Canceled"
msgstr "Annulé"

#: pinakes/main/catalog/models.py:335 pinakes/main/catalog/models.py:422
msgid "Completed"
msgstr "Complété"

#: pinakes/main/catalog/models.py:336 pinakes/main/catalog/models.py:423
msgid "Created"
msgstr "Créé"

#: pinakes/main/catalog/models.py:337 pinakes/main/catalog/models.py:424
msgid "Denied"
msgstr "Refusé"

#: pinakes/main/catalog/models.py:338 pinakes/main/catalog/models.py:425
#: pinakes/main/models.py:67
msgid "Failed"
msgstr "Échec"

#: pinakes/main/catalog/models.py:339 pinakes/main/catalog/models.py:426
msgid "Ordered"
msgstr "Commandé"

#: pinakes/main/catalog/models.py:549
#, python-format
msgid ""
"Created Approval Request ref: %(approval_request_ref)s. Catalog approval "
"request id: %(approval_request_id)s"
msgstr "Demande d’approbation ref: %(approval_request_ref)s créée. Id de demande d’approbation du catalogue : %(approval_request_id)s"

#: pinakes/main/catalog/models.py:569
msgid "undecided"
msgstr "non décidée"

#: pinakes/main/catalog/models.py:570
msgid "approved"
msgstr "approuvée"

#: pinakes/main/catalog/models.py:571
msgid "canceled"
msgstr "annulée"

#: pinakes/main/catalog/models.py:572
msgid "denied"
msgstr "refusée"

#: pinakes/main/catalog/models.py:573
msgid "failed"
msgstr "Échec"

#: pinakes/main/catalog/serializers.py:410
msgid "Order"
msgstr "Commande"

#: pinakes/main/catalog/serializers.py:411
msgid "OrderItem"
msgstr "Article de commande"

#: pinakes/main/catalog/services/cancel_order.py:61
msgid "Order {} is not cancel able in its current state: {}"
msgstr "La commande {} n'est pas annulable dans son état actuel : {}"

#: pinakes/main/catalog/services/collect_tag_resources.py:62
msgid "Portfolio item {} does not have related service offering"
msgstr "L’élément du portefeuille {} n’a pas d’offres de services associées"

#: pinakes/main/catalog/services/copy_portfolio_item.py:47
msgid "{} is not order able, and cannot be copied"
msgstr "{} ne peut pas être commandé, et ne peut pas être copié"

#: pinakes/main/catalog/services/finish_order.py:31
#, python-format
msgid "Order %(order_id)s has failed"
msgstr "La commande %(order_id)s a échoué"

#: pinakes/main/catalog/services/finish_order.py:36
#, python-format
msgid "Order %(order_id)s is completed"
msgstr "La commande %(order_id)s est terminée"

#: pinakes/main/catalog/services/finish_order.py:44
msgid "Order Canceled"
msgstr "Commande annulée"

#: pinakes/main/catalog/services/finish_order.py:48
msgid "Order Failed"
msgstr "Commande échouée"

#: pinakes/main/catalog/services/finish_order.py:53
#, python-format
msgid ""
"This order item has failed due to the entire order %(state)s before it ran"
msgstr "L’élément de la commande a échoué en raison du %(state)s de la commande entière"

#: pinakes/main/catalog/services/finish_order_item.py:34
#, python-format
msgid "Order Item %(id)s is completed"
msgstr "L’élément de la commande %(id)s est complété"

#: pinakes/main/catalog/services/handle_approval_events.py:76
msgid "Internal Error. Please contact our support team."
msgstr "Erreur interne. Veuillez contacter notre équipe d'assistance."

#: pinakes/main/catalog/services/handle_approval_events.py:109
#, python-format
msgid "Approval Request finished with status %(state)s"
msgstr "La demande d’approbation est achevée avec le statut %(state)s"

#: pinakes/main/catalog/services/handle_approval_events.py:115
#, python-format
msgid "Approval Request finished with status %(state)s and reason %(reason)s"
msgstr "La demande d’approbation est achevée avec le statut %(state)s et la raison %(reason)s"

#: pinakes/main/catalog/services/provision_order_item.py:30
#, python-format
msgid "Order Item %(id)s is provisioned"
msgstr "L'élément de commande %(id)s est approvisionné"

#: pinakes/main/catalog/services/sanitize_parameters.py:42
msgid "parameter {} is required and must have a value"
msgstr "Le paramètre {} est requis et doit comporter une valeur"

#: pinakes/main/catalog/services/start_order.py:21
msgid "Submitting Order for provisioning"
msgstr "Commande soumise à exécution"

#: pinakes/main/catalog/services/start_order_item.py:53
#, python-format
msgid "Submitting Order Item %(item_id)s for provisioning"
msgstr "Élément de la commande %(item_id)s soumis à exécution"

#: pinakes/main/catalog/services/submit_approval_request.py:61
msgid "Failed to submit request to approval for Order {}, error: {}"
msgstr "N’a pas pu soumettre de demande d’approbation pour la Commande {}, erreur : {}"

#: pinakes/main/catalog/services/validate_order_item.py:45
msgid ""
"The underlying survey on product {} in the portfolio {} has been changed and "
"is no longer valid, please contact an administrator to reset it."
msgstr "Le questionnaire latent au produit {} qui se trouve dans le portefeuille {} n’a pas changé et n’est plus valide. Veuillez contacter un administrateur pour le corriger."

#: pinakes/main/catalog/views.py:521
msgid "Order {} does not have related order items"
msgstr "La commande {} n’a pas d’éléments de commande associés"

#: pinakes/main/catalog/views.py:531
#, python-format
msgid "Computed tags for order %(order_id)d: %(tag_resources)s"
msgstr "Libellés calculés pour la commande %(order_id)d: %(tag_resources)s"

#: pinakes/main/inventory/exceptions.py:8
msgid "Refresh already registered"
msgstr "Réactualisation déjà enregistrée"

#: pinakes/main/inventory/serializers.py:50
#, python-format
msgid "%(name)s is unavailable, refresh skipped"
msgstr "%(name)s est indisponible, le rafraîchissement est ignoré"

#: pinakes/main/inventory/serializers.py:55
#, python-format
msgid "Refresh failed: %(error)s"
msgstr "Le rafraîchissement a échoué : %(error)s"

#: pinakes/main/inventory/serializers.py:59
msgid "adds"
msgstr "ajoute"

#: pinakes/main/inventory/serializers.py:60
msgid "deletes"
msgstr "supprime"

#: pinakes/main/inventory/serializers.py:61
msgid "updates"
msgstr "mises à jour"

#: pinakes/main/inventory/serializers.py:83
#, python-format
msgid "Service Inventories: %(stats)s;\n"
msgstr "Inventaire des services : %(stats)s;\n"

#: pinakes/main/inventory/serializers.py:88
#, python-format
msgid "Job Templates & Workflows: %(soi_stats)s;\n"
msgstr "Modèles de Jobs de flux de travail : %(soi_stats)s;\n"

#: pinakes/main/inventory/serializers.py:93
#, python-format
msgid "Workflow Template Nodes: %(son_stats)s;\n"
msgstr "Modèle de flux de travail : %(son_stats)s;\n"

#: pinakes/main/inventory/serializers.py:97
#, python-format
msgid "Service Plan: %(sp_stats)s;\n"
msgstr "Plan de service : %(sp_stats)s;\n"

#: pinakes/main/inventory/serializers.py:102
msgid "Nothing to update"
msgstr "Rien à mettre à jour"

#: pinakes/main/inventory/serializers.py:125
#, python-format
msgid ""
"Source cannot be changed to url %(new_url)s uuid %(new_install_uuid)s, "
"currently bound to url %(url)s with uuid %(install_uuid)s"
msgstr "La source ne peut pas être changée en url %(new_url)s uuid %(new_install_uuid)s, actuellement liée à url %(url)s avec uuid %(install_uuid)s"

#: pinakes/main/inventory/serializers.py:131
#, python-format
msgid "Error: %(error)s"
msgstr "Erreur : %(error)s "

#: pinakes/main/inventory/services/collect_inventory_tags.py:38
msgid "ServiceOffering object {} not found"
msgstr "L’objet d’offre de service {} non trouvé"

#: pinakes/main/inventory/services/get_service_offering.py:34
msgid "Failed to get service offering [{}]"
msgstr "N’a pas pu trouver l’offre de service [{}] "

#: pinakes/main/inventory/task_utils/check_source_availability.py:55
msgid "Check availability completed"
msgstr "Vérification de la disponibilité terminée"

#: pinakes/main/inventory/task_utils/launch_job.py:68
#, python-format
msgid "Job %(id)s has %(status)s status"
msgstr "Job %(id)s a pour statut %(status)s "

#: pinakes/main/inventory/views.py:89
msgid "Refresh job {} is already {}, please try again later"
msgstr "Le job de réactualisation {} est déjà {}, veuillez essayer à nouveau ultérieurement"

#: pinakes/main/models.py:65
msgid "Done"
msgstr "Terminé"

#: pinakes/main/models.py:66
msgid "InProgress"
msgstr "EnCours"

#: pinakes/main/models.py:68
msgid "Unknown"
msgstr "Inconnu"

